SELECT e3.ID
FROM ECOLI_DATA e1  -- 1세대 (조부모)
INNER JOIN ECOLI_DATA e2 ON e1.ID = e2.PARENT_ID  -- 2세대 (부모)
INNER JOIN ECOLI_DATA e3 ON e2.ID = e3.PARENT_ID  -- 3세대 (자식)
WHERE e1.PARENT_ID IS NULL  -- 1세대 조건
ORDER BY e3.ID;
